### PR TITLE
[Quality] Reorganize files.

### PR DESCRIPTION
**Pull request by lshqqytiger**
Depends on #4

### CODE REVIEW

**Comment by lshqqytiger** [comment]
Proposed reviewers: @tnraro @andjsrk @logic-finder

**Comment by tnraro** [comment]
It's a good suggestion, but we should exclude the changes that are irrelevant to this PR. The irrelevant files are as follows:

- hhss/README.md
- hhss/cpp/CMakeLists.txt
- hhss/cpp/CMakePresets.json
- hhss/cpp/generator.cpp
- hhss/cpp/generator.h
- hhss/cpp/hhss_cpp.cpp
- hhss/cpp/hhss_cpp.h
- hhss/cpp/random_formatting_map.cpp
- hhss/cpp/random_formatting_map.h
- hhss/hsr.dat
- hhss/usr.dat
- nsy/hip/.clang-format

**Comment by lshqqytiger** [comment]
Every change about hhss will be excluded after #4 is merged.
However, I don't know why `nsy/hip/.clang-format` should be excluded.

**Review by tnraro — APPROVED** [review]
LGTM

**Review by logic-finder — APPROVED** [review]
image
Looks neat!

**Review by andjsrk — APPROVED** [review]

**Review by tnraro — APPROVED** [review]

**Pull request merged**
